etcd:  
  image: gcr.io/google_containers/etcd:3.0.4
  net: host
  command: ['/usr/local/bin/etcd', '--listen-client-urls=http://127.0.0.1:2379', '--advertise-client-urls=http://127.0.0.1:2379', '--data-dir=/var/etcd/data']

apiserver:  
  image: gcr.io/google_containers/hyperkube:v1.4.5
  net: host
  command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--etcd_servers=http://127.0.0.1:2379", '--address=127.0.0.1', '--v=2']

controller:
  image: gcr.io/google_containers/hyperkube:v1.4.5
  net: host
  command: ["/hyperkube", "controller-manager", "--master=127.0.0.1:8080", '--v=2']

scheduler:  
  image: gcr.io/google_containers/hyperkube:v1.4.5
  net: host
  command: ["/hyperkube", "scheduler", "--master=127.0.0.1:8080", '--v=2']

kubelet:  
  image: gcr.io/google_containers/hyperkube:v1.4.5
  net: host
  pid: host
  command: ['/hyperkube', 'kubelet', '--containerized', '--hostname-override=127.0.0.1', '--address=0.0.0.0', '--api-servers=http://localhost:8080']
  privileged: true
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw

proxy:  
  image: gcr.io/google_containers/hyperkube:v1.4.5
  net: host
  command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']
  privileged: true
  volumes:
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
